//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QR
{
    using System;
    using System.Collections.Generic;
    
    public partial class branch_tbl
    {
        public int RecordID { get; set; }
        public Nullable<int> ComID { get; set; }
        public Nullable<int> branchID { get; set; }
        public string Name { get; set; }
        public string country { get; set; }
        public string governate { get; set; }
        public string regionCity { get; set; }
        public string street { get; set; }
        public string buildingNumber { get; set; }
        public string postalCode { get; set; }
        public string floor { get; set; }
        public string room { get; set; }
        public string landmark { get; set; }
        public string additionalInformation { get; set; }
        public string mailFrom { get; set; }
        public string sendrPassword { get; set; }
        public string maillTo { get; set; }
        public string Smtp_Server_Port { get; set; }
        public string Smtp_Server_Host { get; set; }
        public string databaseConnGet { get; set; }
        public string ResponseTableName { get; set; }
        public string ReceiptNumberColumnName { get; set; }
    }
}
