//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QR
{
    using System;
    using System.Collections.Generic;
    
    public partial class branshs_log_tbl
    {
        public int Recourd_Id { get; set; }
        public string ReceiptNumber { get; set; }
        public string ReceiptType { get; set; }
        public string transferDate { get; set; }
        public string Response { get; set; }
        public string uuid { get; set; }
        public string PreviousUuid { get; set; }
        public string ReferenceOldUuid { get; set; }
        public Nullable<byte> sendToETA { get; set; }
        public string validation { get; set; }
        public string submissionUuid { get; set; }
        public string branshId { get; set; }
        public Nullable<int> COMID { get; set; }
        public string posserial { get; set; }
        public string BranchName { get; set; }
        public Nullable<System.DateTime> edit_date { get; set; }
        public Nullable<int> ReceiptNumberAsNumber { get; set; }
        public Nullable<decimal> NetAmount { get; set; }
    }
}
