//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QR
{
    using System;
    using System.Collections.Generic;
    
    public partial class Com_Tbl
    {
        public Nullable<int> id { get; set; }
        public string type { get; set; }
        public Nullable<int> branchID { get; set; }
        public string Name { get; set; }
        public string country { get; set; }
        public string governate { get; set; }
        public string regionCity { get; set; }
        public string street { get; set; }
        public string buildingNumber { get; set; }
        public string postalCode { get; set; }
        public string floor { get; set; }
        public string room { get; set; }
        public string landmark { get; set; }
        public string additionalInformation { get; set; }
        public string taxpayerActivityCode { get; set; }
        public int Recourd_ID { get; set; }
        public Nullable<bool> RunType { get; set; }
        public Nullable<decimal> ArrangeWorkTimes { get; set; }
        public Nullable<System.DateTime> NextRunTime { get; set; }
        public Nullable<bool> RunStutes { get; set; }
        public string ClientId { get; set; }
        public string editor { get; set; }
        public string dashboardConnGet { get; set; }
        public string TypeVersion { get; set; }
        public Nullable<int> SendToEtaWay { get; set; }
        public Nullable<int> ItemFlag { get; set; }
        public Nullable<int> PriceFlag { get; set; }
        public string Password { get; set; }
    }
}
