//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QR
{
    using System;
    using System.Collections.Generic;
    
    public partial class dbo_Scopos_error_log_tbl
    {
        public int Record_Id { get; set; }
        public string ReceiptNumber { get; set; }
        public string uuid { get; set; }
        public string message { get; set; }
        public string target { get; set; }
        public string Response { get; set; }
    }
}
