//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QR
{
    using System;
    using System.Collections.Generic;
    
    public partial class ETA_document_Tbl
    {
        public Nullable<int> Com_TAX_No { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<int> Environment_ID { get; set; }
        public string Environment { get; set; }
        public string documentTypeVersion { get; set; }
        public string documentType { get; set; }
        public string Login_URL { get; set; }
        public string client_id { get; set; }
        public string client_secret { get; set; }
        public string client_secret_2 { get; set; }
        public string TokenPin { get; set; }
        public string DocumentSubmissions_URL { get; set; }
        public int Recourd_Id { get; set; }
        public string TokenCompny { get; set; }
        public string editor { get; set; }
    }
}
