//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QR
{
    using System;
    using System.Collections.Generic;
    
    public partial class Integrate_setup_tbl_New
    {
        public int Record_ID { get; set; }
        public Nullable<int> Com_Tax_No { get; set; }
        public Nullable<byte> DataSourceType { get; set; }
        public Nullable<byte> DataResponseType { get; set; }
        public Nullable<byte> InsertResponse { get; set; }
        public string ExelFilePath { get; set; }
        public string ExelFileBackupPath { get; set; }
        public string ExelFileName { get; set; }
        public string ExelTabName { get; set; }
        public string Mail { get; set; }
        public string fillGV { get; set; }
        public string FillDashboard { get; set; }
        public string SearchInvent_1 { get; set; }
        public string SearchInvent_2 { get; set; }
        public string SetResponse_TableName { get; set; }
        public string SetResponse_Response_ColName { get; set; }
        public string SetResponse_validation_ColName { get; set; }
        public string SetResponse_sendToetaStatus_ColName { get; set; }
        public string SetResponse_sendToetaDate_ColName { get; set; }
        public string SetResponse_InvNo_ColName { get; set; }
        public string SetResponse_RecourdID_ColName { get; set; }
        public string DataSourceQuery_H_Re_Submit_Issues { get; set; }
        public string DataSourceQuery_H { get; set; }
        public string DataSourceQuery_D { get; set; }
        public string InsertResponseQuery { get; set; }
        public string GetAllValid_Query { get; set; }
        public string GetAllInValid_Query { get; set; }
        public string GetAllSubmet_Query { get; set; }
        public string GetAllUnSubmet_Query { get; set; }
        public string GetAllUnCanceld_Query { get; set; }
        public string GetAllUnReject_Query { get; set; }
        public string FillDashPord { get; set; }
        public string Linlk_H_With_D_By_ColName { get; set; }
        public string GetReportSales { get; set; }
        public string GetReportPurchases { get; set; }
        public string Select_Coll_29 { get; set; }
        public string Select_Coll_30 { get; set; }
        public string Select_Coll_31 { get; set; }
        public string Select_Coll_32 { get; set; }
        public string Select_Coll_33 { get; set; }
        public string Select_Coll_34 { get; set; }
        public string Select_Coll_35 { get; set; }
        public string Select_Coll_36 { get; set; }
        public string Select_Coll_37 { get; set; }
        public string Select_Coll_38 { get; set; }
        public string Select_Coll_39 { get; set; }
        public string Select_Coll_40 { get; set; }
        public string editor { get; set; }
        public string SetResponseDB { get; set; }
        public string DataSource_Conn { get; set; }
        public string CallApi_URL { get; set; }
        public string CallApi_CONSUMERKEY { get; set; }
        public string CallApi_CONSUMERSECRET { get; set; }
        public string CallApi_TOKENKEY { get; set; }
        public string CallApi_TOKENSECRET { get; set; }
        public string CallApi_Realm { get; set; }
        public string CallApi_script { get; set; }
        public string CallApi_deploy { get; set; }
        public Nullable<int> CallApi_ComID { get; set; }
    }
}
