//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QR
{
    using System;
    using System.Collections.Generic;
    
    public partial class LicenseTbl
    {
        public int Recourd_ID { get; set; }
        public string ComName { get; set; }
        public string TaxNumber { get; set; }
        public string DBName { get; set; }
        public string DBAccount { get; set; }
        public string DBPassword { get; set; }
        public string SetteingDBNAME { get; set; }
        public string Conn { get; set; }
        public string Logger { get; set; }
    }
}
