//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QR
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment_Point_Tbl
    {
        public int RecordID { get; set; }
        public Nullable<decimal> ActualAmount { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public string Editor { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string PaymentMethod { get; set; }
        public Nullable<int> SettlementType { get; set; }
        public Nullable<int> BillNo { get; set; }
        public string CheckDetails { get; set; }
        public string Currency { get; set; }
        public Nullable<int> CollectionPeriod { get; set; }
        public Nullable<decimal> Penalty { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<decimal> SupplyExpenses { get; set; }
        public Nullable<decimal> Other { get; set; }
    }
}
