//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QR
{
    using System;
    using System.Collections.Generic;
    
    public partial class PosMachin_tbl
    {
        public Nullable<int> comid { get; set; }
        public Nullable<int> branchID { get; set; }
        public Nullable<int> POS_id { get; set; }
        public Nullable<System.DateTime> LicenseExpiryDate { get; set; }
        public string POSName { get; set; }
        public string posserial { get; set; }
        public string clintId { get; set; }
        public string scId { get; set; }
        public string pososversion { get; set; }
        public Nullable<bool> status { get; set; }
        public int RecordID { get; set; }
        public Nullable<byte> ENVIRONMENT { get; set; }
        public string AndroidID { get; set; }
        public Nullable<bool> licenseStatus { get; set; }
        public string databaseConnGet { get; set; }
        public string databaseConnSet { get; set; }
        public Nullable<byte> DBSetType { get; set; }
        public Nullable<byte> DBGetType { get; set; }
        public Nullable<System.DateTime> LastRunning { get; set; }
    }
}
