//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QR
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registeration_Request_Tbl
    {
        public int RecordID { get; set; }
        public string CompanyName { get; set; }
        public string BranchName { get; set; }
        public Nullable<int> BranchID { get; set; }
        public string AndroidID { get; set; }
        public string PosSerial { get; set; }
        public Nullable<byte> Status { get; set; }
        public Nullable<int> ComID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    }
}
