//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QR
{
    using System;
    using System.Collections.Generic;
    
    public partial class RunningLog_tbl
    {
        public int Record_Id { get; set; }
        public Nullable<System.DateTime> running_time { get; set; }
        public Nullable<int> branshId { get; set; }
        public string BranchName { get; set; }
        public Nullable<int> inv_count { get; set; }
        public string running_feadback { get; set; }
        public Nullable<int> SellerRin { get; set; }
    }
}
