//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QR
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblAssignComp
    {
        public Nullable<int> Comp_TAX_No { get; set; }
        public Nullable<int> Group_RecordID { get; set; }
        public int RecordID { get; set; }
        public Nullable<int> AuthenticationRequired { get; set; }
        public Nullable<int> Com_ID { get; set; }
    }
}
