//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QR
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblDeal
    {
        public Nullable<int> MOBILE { get; set; }
        public Nullable<decimal> OVD { get; set; }
        public Nullable<System.DateTime> DEAL_DATE { get; set; }
        public Nullable<System.DateTime> NEW_EMI_DATE { get; set; }
        public Nullable<decimal> DEAL_AMOUNT { get; set; }
        public Nullable<decimal> DEPOSIT { get; set; }
        public Nullable<decimal> NEW_EMI { get; set; }
        public Nullable<System.DateTime> C1ST_MONTH { get; set; }
        public Nullable<int> TENOR { get; set; }
        public Nullable<decimal> WAIVED_AMOUNT { get; set; }
        public string ACTION_TRUE { get; set; }
        public string LEGAL { get; set; }
        public string LETTER { get; set; }
        public string CALL_RECORDED_TIME { get; set; }
        public string EXT { get; set; }
        public string AGENCY { get; set; }
        public string OFFICER { get; set; }
        public string NOTES { get; set; }
        public string user_name { get; set; }
        public Nullable<System.DateTime> Time { get; set; }
        public Nullable<int> ACC { get; set; }
        public Nullable<int> ID { get; set; }
        public int RecordID { get; set; }
        public string CUSTOMER { get; set; }
    }
}
