//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QR
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblFunction
    {
        public string FunctionName { get; set; }
        public string Description { get; set; }
        public int RecordID { get; set; }
        public Nullable<int> AuthenticationRequired { get; set; }
        public Nullable<int> Perm { get; set; }
    }
}
