//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QR
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblPasswordHistory
    {
        public string Password { get; set; }
        public Nullable<int> User_RecordID { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
        public int RecordID { get; set; }
    }
}
